---
title: "Topics in Credibility Notes"
---

<style>
  div {border-radius: 10px; padding: 10px}
  div.red    {background-color:rgba(255, 199, 199, 1)}
  div.lr     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255, 69, 69,   0.3));}
  div.orange {background-color:rgba(255, 224, 199, 1)}
  div.lo     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255, 165, 0,   0.3));}
  div.yellow {background-color:rgba(255, 248, 199, 1)}
  div.ly     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255, 255, 0,   0.3));}
  div.green  {background-color:rgba(215, 255, 199, 1)}
  div.lg     {background-image: linear-gradient(to right, rgba(215, 255, 199,1), rgba(111, 255, 54,  0.4));}
  div.blue   {background-color:rgba(199, 233, 255, 1)}
  div.lb     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(84,  188, 255, 0.3));}
  div.purple {background-color:rgba(229, 199, 255, 1)}
  div.lp     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(176, 88, 252,  0.3));}
  div.gray   {background-color:rgba(253, 253, 253, 1)}
  div.lg     {background-color:rgba(253, 253, 253, 0.5)}
  div.white  {background-color:rgba(255, 255, 255, 1)}
  div.ja     {background-color:rgba(250, 250, 250, 1)}
</style>

$\newcommand\given[1][]{\:#1\vert\:}$


<div class = "ja">

<div class = "ja">

# 1: Credibility Models

<div class = "purple">

## 1.1: An Intuitive Model for Credibility

- The actuary uses observations of events that happened in the past to forecast future events or costs

- Classes are groupings of risks with similar risk characteristics; though similar, each risk is still unique

- Class rating is often supplemented with experience rating so that the insurance premium for an individual risk is based on both the class rate and actual past loss experience for the risk

<div class = "lp">

### 1.1.1: Balance between Class Rating and Individual Risk Experience

#### How homogeneous are the classes?

- Within-class risks very similar $\rightarrow$ class rate more important

- Within-class risks significantly different $\rightarrow$ individual risk experience more important

- <mark>***Hypothetical mean*** = individual risk mean</mark>

- <mark>***Variance of Hypothetical Means (VHM)*** = statistical measure for the risk homogeneity (or lack thereof) within a class</mark>

- small VHM $\rightarrow$ more class homogeneity $\rightarrow$ more weight to class than individual

#### How much variation is there in an individual risk's loss experience?

- <mark>***Process variance*** = the variance of an individual risk</mark>

- If there is a large amount of variation expected in the actual loss experience for an individual risk, then individual risk experience may not be a useful estimator

- <mark>***Expected Value of the Process Variance (EPV)*** = the average of the process variance over the entire class of risks</mark>

#### Derivation of Bühlmann Credibility

Let $i$ be a randomly selected risk with $n$ observations. The process variance of an observation of $i$ is $PV_i$. Then,

$$
  \begin{align}
  \text{Sample Mean of Risk } i &=  \bar{X}_i \\ \\
  \text{Var}(\bar{X}_i) &= \dfrac{PV_i}{n} \\ \\
  \text{Estimator of Variance of } \ i &= \text{E}\left[ \dfrac{PV_i}{n}\right] = \dfrac{\text{E}[PV_i]}{n} = \dfrac{EPV}{n} 
  \end{align}
$$

<mark>Let $\mu$ represent the overall class mean</mark>. Then, the variance of the individual risk means about $\mu$ is $VHM$. 

Then, we can define the expected value of the $i^{\text{th}}$ risk as a weighted average of the risk's mean, $\bar{X}_i$, and the class mean, $\mu$:

$$
  \text{Estimate} = w \cdot \bar{X}_i + (1-w) \cdot \mu
$$
Optimally, we choose weights proportional to the reciprocals of their respective variances. If we define $K \equiv \dfrac{EPV}{VHM}$, we get:

$$
  w = \dfrac{n}{n+K}
$$
This is the familiar Bühlmann Credibility formula: $Z = \dfrac{n}{n+K}$!


#### Preliminaries and Notation

- The actual observation during time $t$ for that particular risk or group will be denoted by $x_t$, which is the observation of corresponding random variable, $X_t$

- $X_t$ may represent:

  - Number of claims in period $t$
  
  - Loss ratio in year $t$
  
  - Loss per exposure in year $t$
  
  - Outcome of the $t^{\text{th}}$ roll of a die

- An individual risk is a member of a larger population and has an associated risk parameter, $\theta$, which is a specific value of the randomly distributed random variable, $\Theta$

- <mark>The distribution of $X_t$ depends on $\theta$ $\left(\text{i.e., } f_{X|\Theta}(x_t \given \theta)\right)$</mark>

  - **Example**: Number of claims, $X_t$, is a Poisson process with mean $\theta$
  
  - $f_{X|\Theta} \sim \text{Pois}(\theta)$

- <mark>***Conditional Expectation of $X_t$***: $\text{E}_{X|\Theta}[X_t \given\Theta = \theta] = \int x_t \cdot f_{X|\Theta}(x_t \given \theta) \ dx_t = \mu(\theta)$</mark>

- <mark>The risk parameter represented by the random variable $\Theta$ has its own probability density function, $f_\Theta (\theta)$, which described how the risk characteristics are distributed within the population</mark>

- <mark>***Unconditional Expectation of $X_t$***: $\text{E}[X_t] = \int \int x_t \cdot f_{X,\Theta} (x_t,\theta) \ dx_t \ d\theta = \dots = \text{E}_\Theta[\text{E}_{X|\Theta}[X_t \given \Theta]] = \text{E}_\Theta[\mu(\theta)] = \mu$</mark>

- <mark>***Conditional Variance of $X_t$***: $\text{Var}_{X|\Theta}[X_t \given \Theta=\theta] = \text{E}_{X|\Theta}[(X_t - \mu(\theta))^2 \given \Theta = \theta] = \dots =  \sigma^2(\theta)$ </mark> <br><font color = "darkblue">***(^ Process Variance)***</font>

- <mark>***Unconditional Variance of $X_t$***: $\text{Var}[X_t] = \text{Var}_\Theta[\text{E}_{X|\Theta}[X_t \given \Theta]] + \text{E}[\text{Var}_{X|\Theta}[X_t \given \Theta]]$</mark>
<br><font color = "darkblue">***(^ Total Variance = VHM + EPV)***</font>

- <mark><font color = "red">***See Example on p. 8-9*** for sample calculations [important!]</font></mark>


</div>


</div><br>

<div class = "blue">

## 1.2: Bühlmann Model

- The Bühlmann model assumes that for any selected risk, the random variables $\{X_1,X_2,\dots \}$ are ***independently and identically distributed (i.i.d)***

- ***Homogeneity in time***: $X_t$ has the same probability distribution for any time, $t$, including future outcomes

- $\theta$ is assumed to be constant

<div class = "lb">

### 1.2.1: Assumptions of Bühlmann Credibility

$$
  \begin{align} 
    \textbf{Hypothetical Mean: }& \quad \mu(\theta) = \text{E}_{X|\Theta}[X_1 \given \theta] = \dots = \text{E}_{X|\Theta}[X_N \given \theta] = \text{E}_{X|\Theta}[X_{N+1} \given \theta] = \dots \\ \\
    \textbf{Process Variance: }& \quad \sigma^2(\theta) = \text{Var}_{X|\Theta}[X_1 \given \theta] = \dots = \text{Var}_{X|\Theta}[X_N \given \theta] = \text{Var}_{X|\Theta}[X_{N+1} \given \theta] = \dots 
  \end{align}
$$

</div><br>

<div class = "lb">

### 1.2.2: Formulation of the  Model

$$
  \begin{align}
    \textbf{Population Mean: }& \quad \mu = \text{E}_{\Theta}[\mu(\theta)] = \text{E}_\Theta[\text{E}_{X|\Theta}[X_t \given \theta]]\\ \\
    \textbf{Expected Value of Process Variance: }& \quad EPV = \text{E}_\Theta[\sigma^2(\theta)] = \text{E}_{\Theta}[\text{Var}_{x|\Theta}[X_t \given \theta]]\\ \\
    \textbf{Variance of Hypothetical Means: }& \quad VHM = \text{Var}_\Theta[\mu(\theta)] = \text{E}_\Theta[(\mu(\theta)-\mu)^2] 
  \end{align}
$$

- <mark>Because $\mu(\theta)$ is unknown for the selected risk, the mean, $\bar{X} = 1/N \cdot \sum_{t=1}^N X_t$ is used. It's an unbiased estimator, since $\text{E}_{X|\Theta}[\bar{X} \given \theta] = \mu(\theta)$</mark>

$$
  \begin{align}
    \textbf{Conditional Variance of } \bar{X} \text{: }& \quad \text{Var}_{X|\Theta}[\bar{X} \given \theta] = \dfrac{\sigma^2(\theta)}{N}\\ \\ 
    \textbf{Unconditional Variance of } \bar{X} \text{: }& \quad \text{Var}[\bar{X}] = VHM + \dfrac{EPV}{N}
  \end{align}
$$

- <mark>***Bühlmann Credibility assigned to $\bar{X}$***: $Z = N/(N+K)$, where $N$ is the number of observations for the risk and $K = EPV/VHM$</mark>

$$
  Z = \dfrac{\text{Variance of the Hypothetical Means}}{\text{Total Variance of the Estimator, } \bar{X}} = \dfrac{\text{Var}[\mu(\theta)]}{\text{Var}[\bar{X}]}
$$

- <mark>***The credibility-weighted estimate for $\mu(\theta) = \text{E}_{X|\Theta}[X_t \given \theta]$***, for $t = 1,2,\dots,N,N+1,\dots$ is $\hat{\mu}(\theta) = Z \cdot \bar{X} + (1-Z) \cdot \mu$</mark>

- $\hat{\mu}(\theta)$ is the least-squares estimator of $\mu(\theta)$

</div><br>

</div><br>

<div class = "orange">

## 1.3: Bühlmann-Straub Model

- The requirement that the random variables, $X_i$, be identically distributed is easily violated in the real world. For example:

  - The work force of a workers compensation policyholder may change in size from one year to the next
  
  - The number of vehicles owned by a commercial automobile policyholder may change through time
  
  - The amount of earned premium for a rating class varies from year to year
  
- A risk's exposure to loss may vary; it is assumed that this exposure can be measured. Some examples:

  - Amount of insurance premium
  
  - Number of employees
  
  - Payroll
  
  - Number of insured vehicles
  
  - Number of claims

- <mark>A fundamental premise of insurance rating is that exposure bases can be identified that are directly related to the potential for loss</mark>

- <mark>The Bühlmann-Straub model assumes that the means of the random variables are equal for the selected risk, but that the process variances are inversely proportional to the size (i.e., exposure) of the risk during each observation period</mark>

<div class = "lo">

$$
  \begin{gather*}
    &\textbf{Assumptions of Bühlmann-Straub Credibility} \\ \\
    & \text{Period } 1 & \text{Period } N & \\ \\
    \hline \\
    \text{Exposure} & m_1 & m_N \\ \\
    \text{Hypothetical Mean for Risk } \theta \\ \text{ per Unit of Exposure} & \mu(\theta) =\text{E}_{X|\Theta}[X_1 \given \theta] = \dots & =\text{E}_{X|\Theta}[X_N \given \theta]  \\ \\
    \text{Process Variance for Risk } \theta & \text{Var}_{X|\Theta}[X_1 \given \theta] = \dfrac{\sigma^2(\theta)}{m_1} &  \text{Var}_{X|\Theta}[X_N \given \theta] = \dfrac{\sigma^2(\theta)}{m_N} 
  \end{gather*}
$$

</div><br>

- <mark>$X_t$ represent number of claims, monetary losses, or some other quantity of interest ***per unit of exposure*** (e.g., the number of claims per house-year, or a loss ratio), and $m_t$ is the measure of exposure (e.g., car-miles)</mark>

- <mark>Process variance decreases as exposure increases</mark>

- How should random variables $\{ X_1, X_2, \dots, X_N \}$ be combined to estimate the hypothetical mean $\mu(\theta)$? A weighted average using the exposures, $m_t$, will give a linear estimator for $\mu(\theta)$ with minimum variance. 

- <mark>Let $m$ be total exposures and $\bar{X}$ be a weighted average of each $X_i$ based on its exposures</mark>:

$$
  \begin{align}
    m &= \sum_\limits{t=1}^N m_t \\
    \bar{X} &= \sum_{t=1}^N \left( \dfrac{m_t}{m}\right) \cdot X_t
  \end{align}
$$ 

$$
  \begin{align}
  \textbf{Conditional Expected Value of } \bar{X}:& \quad \text{E}_{X|\Theta}[\bar{X} \given \theta] = \dots = \sum_{t=1}^N \left( \dfrac{m_t}{m} \right) \cdot \mu(\theta) = \mu(\theta) \\ 
  \textbf{Conditional Variance of } \bar{X}:& \quad \text{Var}_{X|\Theta}[\bar{X} \given \theta] = \dots = \sum_{t=1}^N \left( \dfrac{m_t}{m} \right)^2 \cdot \left( \dfrac{\sigma^2(\theta)}{m_t} \right) = \dfrac{\sigma^2(\theta)}{m} \\ 
    \textbf{Expected Value of Process Variance} :& \quad EPV = \text{E}_\Theta[\sigma^2(\theta)]\\ \\
    \textbf{Variance of Hypothetical Means} : & \quad VHM = \text{Var}_\Theta[\mu(\theta)] \\ \\
    \textbf{Unconditional Expected Value of } \bar{X} :& \quad  \text{E}[\bar{X}] = \text{E}[\mu(\theta)] = \mu\\ \\
    \textbf{Unconditional Variance of } \bar{X} :& \quad \text{Var}[\bar{X}] = VHM + \dfrac{EPV}{m}
  \end{align}
$$


- <mark>***Bühlmann-Straub Credibility***: $Z = m/(m+K)$</mark>

- $K = EPV/VHM = \text{E}_\Theta[\sigma^2(\Theta)]/\text{Var}_\Theta[\mu(\Theta)]$

- <mark>The Bühlmann model is a special case of the more general Bühlmann-Straub model, with $m_t = 1$ for all $t$.</mark>

- <mark>***Credibility-Weighted Estimate for $\mu(\theta)$***: $\hat{\mu}(\theta) = Z \cdot \bar{X} + (1-Z) \cdot \mu$</mark>

</div>

</div>

<div class = "ja">

# 2: Estimation of Credibility Formula Parameters

<div class = "blue">

## 2.1: Requirements for Determining Credibility

- Both the Bühlmann- and Bühlmann-Straub models require a determination of the parameter $K$. This can be done in one of the following ways:

  - Judgmentally select $K$
  
  - Select a value of $K$ that would have worked best in prior applications of the model
  
  - Attempt to determine the $EPV$ and $VHM$ components of $K$
  
- Determining $EPV$ and $VHM$ is the chosen method. To do so, the following are needed:

  - Process variances, $\sigma^2(\theta)$, for each risk in the population 
  
  - Hypothetical means, $\mu(\theta)$, for each risk in the population
  
  - Distribution function for $\theta$ to calculate the $EPV = \text{E}_\Theta[\sigma^2(\theta)]$ and $VHM = \text{Var}_\Theta[\mu(\theta)]$

### Additional Assumptions for Determining EPV and VHM

- <mark>Let there be $R$ independent risks observed for $N$ separate time periods, each with its own risk parameter, $\theta_i$</mark>

- <mark>$X_{it}$ are random variables representing losses or number of claims for risk $i$ during time period $t$</mark>

- $\text{E}_{X|\Theta}[X_{it} \given \theta_i] = \mu(\theta_i)$

- For any selected risk, $i$, the $X_{it}$'s are independent, given $\Theta_i = \theta_i$

- The outcomes for any risk are independent of any other risk

- <mark>The random variables, $\Theta_1, \Theta_2, \dots, \Theta_R$, are independent and identically distributed from a common distribution, $f_\Theta(\theta)$</mark>

- $\text{E}[X_{it}] = \text{E}_\Theta[\text{E}_{X|\Theta}[X_{it} \given \Theta_i]] = \text{E}_\Theta[\mu(\Theta_i)] = \mu$

</div><br>

<div class = "green">

## 2.1: Non-parametric Estimation

- In the non-parametric case, no assumptions are made about the form or parameters of the distributions of $X_it$, nor are any assumptions made about the distribution of the risk parameters, $\Theta_i$

- <mark>In practice, the $EPV$ and $VHM$ are often unknown, but can be estimated from the data for the Bühlmann- or Bühlmann-Straub models, using empirical Bayesian procedures (i.e., Bayes estimation)</mark>

<div class = "lg">

### 2.1.1: Estimating $EPV$ and $VHM$ using the Bühlmann Model

- Estimates of the $EPV$ and $VHM$ can be made from empirical observations about a sample from the population of risks

- Assume there are $R$ risks in the sample with $N$ separate observations for each risk. The random variables, $X_it$, represent the observed values (e.g., claims) for risk $i$ at time $t$. Then, $\forall i \in \{1,2,\dots, R\}$:

$$
  \begin{align}
    \textbf{Risks' Sample Means: } \quad \bar{X}_i &= \left( \dfrac{1}{N}\right) \sum_{t=1}^N X_{it} \\
    \textbf{Risks' Sample Process Variances: } \quad \hat{\sigma}^2_i &= \left( \dfrac{1}{N-1}\right) \sum_{t=1}^N (X_{it} - \bar{X}_i)^2
  \end{align}
$$

- <mark>$\bar{X}_i$ are unbiased estimators for each risk's mean, $\mu(\theta_i)$</mark>

- <mark>$\hat{\sigma}^2_i$ are unbiased estimators for each risk's process variance, $\sigma^2(\theta_i)$</mark>

<div class = "green">

$$
  \widehat{EPV} = \left( \dfrac{1}{R} \right) \sum_\limits{i=1}^R \hat{\sigma}^2_i = \left( \dfrac{1}{R\cdot (N-1)} \cdot  \sum_{i=1}^R \sum_{t=1}^N (X_{it} - \bar{X}_i)^2  \right)
$$

</div><br>

- The $R$ risks are all independent, so $\bar{X}_i$ are independent

- Unbiased estimator for the variance of $\bar{X}_i$ is:

$$
  \widehat{\text{Var}}[\bar{X}_i] = \left( \dfrac{1}{R-1}\right) \cdot \sum_{i=1}^R (\bar{X}_i - \bar{X})^2, \quad \text{where} \quad \bar{X} = \dfrac{1}{R} \cdot \sum_{i=1}^R \bar{X}_i
$$

- $VHM = \text{Var}[\bar{X}_i] - EPV/N$, so substituting or estimator for $EPV$, we get an estimator for the $VHM$:

<div class = "green">

$$
  \widehat{VHM} = \left( \dfrac{1}{R-1}\right) \sum_{i=1}^R (\bar{X}_i - \bar{X})^2 - \left\{ \left( \dfrac{1}{R\cdot (N-1)}\right) \cdot \sum_{i=1}^R \sum_{t=1}^N (X_{it} - \bar{X}_i)^2 \right\}/N
$$

</div><br>

- <mark>If $\widehat{VHM}$ is negative, conclude $VHM=0 \rightarrow \hat{Z} = 0$</mark>

<div class = "green">

$$
  \hat{K} = \dfrac{\widehat{EPV}}{\widehat{VHM}} \qquad \qquad\hat{Z} = \dfrac{N}{N+\hat{K}} \qquad \qquad \hat{\mu}(\theta_i) = \hat{Z} \cdot \bar{X}_i + (1-\hat{Z}) \cdot \bar{X}
$$

- Even though our estimators of $EPV$ and $VHM$ are unbiased, <mark>***$\hat{Z}$ is biased***</mark>. With that said, $\hat{Z}$ is generally accepted as a reasonable estimate for the credibility weight

</div><br>

</div><br>

<div class = "lg">

### 2.1.2: Estimating $EPV$ and $VHM$ using the Bühlmann-Straub Model

- In the case of Bühlmann-Straub, things get more challenging

- <mark>Recall that ***$X_{it}$ represent frequencies*** (e.g., claim frequencies, loss ratios, average cost per exposure)</mark>

- <mark>The number of periods can vary by risk, and the experience periods may start at different times</mark>

- <mark>Let the number of periods for risk $i$ be $N_i$. Then, define $m_i = \sum_\limits{t=1}^{N_i} m_{it}$ and $m = \sum_\limits{i=1}^R m_i$</mark>

- We can then calculate the sample means and estimates for variance as follows:

$$
  \begin{align}
    \textbf{Risks' Sample Means: } \quad \bar{X}_i &= \left( \dfrac{1}{m_i}\right) \sum_{t=1}^{N_i} m_{it} \cdot X_{it} \\ \\
    \textbf{Risks' Sample Process Variances: } \quad \hat{\sigma}^2_i &=  \left( \dfrac{1}{N_i-1}\right) \cdot \sum_{t=1}^{N_i} m_{it} \cdot (X_{it} - \bar{X}_i)^2   
  \end{align}
$$

- If we define the weights <mark>$w_i = (N_i-1)/\left(\sum_{i=1}^R (N_i - 1) \right)$</mark>, the (weighted, by number of exposures) averages of the above two statistics are important:

<div class = "green">

$$
  \begin{align}
    \bar{X} &= \sum_{i=1}^R \dfrac{m_i \cdot \bar{X}_i}{m} \\ \\
    \widehat{EPV} &= \sum_{i=1}^R w_i \cdot \hat{\sigma}_i^2 = \left( \dfrac{\sum_\limits{i=1}^R \sum_\limits{t=1}^{N_i} m_{it} \cdot (X_{it}- \bar{X}_i)^2}{\sum_\limits{i=1}^R (N_i - 1)}\right)
  \end{align}
$$

</div><br>

- <mark>The mean, $\mu(\theta_i)$ is assumed to be constant through time</mark>

- <mark>$\bar{X}_i$ is an unbiased estimator for the mean of risk $i$</mark>

- <mark>$\widehat{EPV}$ is an unbiased estimator for the $EPV$</mark>

- <mark>If $m_{it}\equiv1$ and each risk has the same number of years of data, then the estimator, $\bar{X}_i$ and $\hat{\sigma}^2_i$ match those from the Bühlmann model</mark>

- Deriving an unbiased estimator of $VHM$ is challenging, but it yields the following:

<div class = "green">

$$
  \widehat{VHM} = \dfrac{\left[ \sum_\limits{i=1}^R m_i \cdot (\bar{X}_i - \bar{X})^2 \right] - \left[(R-1) \cdot \widehat{EPV}\right]}{m - \dfrac{1}{m} \cdot \sum_\limits{i=1}^R m_i^2}
$$

</diV><br>

- Finally, we can estimate $K$, $Z_i$, and $\mu(\theta_i)$ as follows:

<div class = "green">

$$
  \hat{K} = \dfrac{\widehat{EPV}}{\widehat{VHM}} \qquad \qquad \hat{Z}_i = \dfrac{m_i}{m_i + K} \qquad \qquad \hat{\mu}(\theta_i) = \hat{Z}_i \cdot \bar{X}_i + (1-\hat{Z}_i) \cdot \bar{X}
$$

</div><br>

#### Balancing the Estimators (if applicable)

- <mark>It is desirable in many cases for the estimators, $\hat{\mu}(\theta)_i$, when weighted together, to equal the overall sample mean, $\bar{X}$. To do so, we define:</mark>

<div class = "green">

$$
  \hat{\mu} = \dfrac{\sum_\limits{i=1}^R \hat{Z}_i \cdot \bar{X}_i}{\sum_\limits{i=1}^R \hat{Z}_i}
$$

</div><br>

- Our new, balanced, credibility estimates become:

<div class = "green">

$$
  \hat{\mu}(\theta_i) = \hat{Z}_i \cdot \hat{X}_i + (1-\hat{Z}_i) \cdot \hat{\mu}
$$

</div><br>

</div><br>

</div><br>

</div>

<div class = "purple">

## 2.2: Semi-parametric Estimation

- What if $X_{it}$ have a specific probability distribution, like Poisson or Binomial? Calculations could become easier!

### Some Assumptions

- <mark>Let $X_{it}$ be ***claims per exposure***; then, $m_{it} \cdot X_{it}$ is the number of claims for risk $i$ in time period $t$</mark>

- <mark>The number of claims is ***Poisson-distributed***</mark>

### Consequential Alterations to Preceding Calculations

- We know that for a Poisson process, it's parameter equals its mean and its variance

- It then follows that (<mark>see p. 29 for derivation</mark>):

<div class = "lp">

$$
  \text{E}_{X|\Theta} [X_{it} \given \theta_i] = m_{it} \cdot \text{Var}_{X|\Theta}[X_{it} \given \theta_i] \\= \theta_i = \mu(\theta_i) = \sigma^2(\theta_i)
$$
</div><br>


- And also:

<div class = "lp">

$$
  \begin{align}
    \mu &= \text{E}_\Theta [\mu (\Theta_i)] = EPV\\
    \hat{\mu} &= \bar{X} \\ \\ 
    \therefore \widehat{EPV} &= \bar{X} 
  \end{align}
$$
</div><br>

- <mark><font color = "red">***Review carefully the Example starting on p.30!***</font></mark>

</div>

</div>

<div class = "ja">

# 3: Conclusion

<div class = "red">

- In practice, using the most precise credibility parameter estimate, versus a reasonable estimate, should not affect final results that much

- Sometimes (if, for instance, population mean is highly variable), it's useful to choose an alternative to population mean as the complement to credibility (what's multiplied by $1-Z$)

- Constant mean, $\mu(\theta)$ is not always relevant 

- Risk heterogeneity is another practical issue: a big risk is not necessarily the sum of smaller, independent risks

</div><br>

</div>

</div>