---
title: "Exam STAM Notes"
---

<style>
  div {border-radius: 10px; padding: 10px; border: 5px solid white}
  div.red    {background-color:rgba(255, 199, 199, 1)}
  div.lr     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255, 69, 69,0.3));}
  div.orange {background-color:rgba(255, 224, 199, 1)}
  div.lo     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255,165,0,0.3));}
  div.yellow {background-color:rgba(255, 248, 199, 1)}
  div.ly     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(255,255,0, 0.3));}
  div.green  {background-color:rgba(215, 255, 199, 1)}
  div.lg     {background-image: linear-gradient(to right, rgba(215, 255, 199, 1), rgba(111, 255, 54, 0.4));}
  div.blue   {background-color:rgba(199, 233, 255, 1)}
  div.lb     {background-image: linear-gradient(to right, rgba(199, 233, 255, 1), rgba(84, 188, 255, 0.3));}
  div.purple {background-color:rgba(229, 199, 255, 1)}
  div.lp     {background-image: linear-gradient(to right, rgba(255,0,0,0), rgba(176, 88, 252, 0.3));}
  div.gray   {background-color:rgba(253, 253, 253, 1)}
  div.lg     {background-color:rgba(253, 253, 253, 0.5)}
  div.white  {background-color:rgba(255, 255, 255, 1)}
  div.ja     {background-color:rgba(200, 200, 200, 1)}
</style>

<style>
  .purple:hover {border: 5px solid black}
  .blue:hover {border: 5px solid black}
  .green:hover {border: 5px solid black}
  .yellow:hover {border: 5px solid black}
  .orange:hover {border: 5px solid black}
</style>

<style>
  a:link {
    color: black;
    background-color: transparent;
    text-decoration: none;
  }
  a:visited {
    color: black;
    background-color: transparent;
    text-decoration: none;
  }
  a:hover {
    color: black;
    background-color: transparent;
    text-decoration: none;
}
</style

<div class = "ja">

<div class = "purple">

# [Loss Models](Loss Models.html)

</div><br>

<div class = "blue">

# [Foundations of CAS](Foundations of Casualty Actuarial Science.html)

</div><br>

<div class = "green">

# [Individual Health Insurance](Individual Health Insurance.html)

</div><br>

<div class = "yellow">

# [Ratemaking and Loss Reserving](Introduction to Ratemaking and Loss Reserving for Property and Casualty Insurance.html)

</div><br>

<div class = "orange">

# [Topics in Credibility](Topics in Credibility.html)

</div>


</div>